spring:
  application:
    name: ImageLibrary
  datasource:
    url: jdbc:postgresql://localhost:5432/imagelibrary
    username: postgres
    password: 4521JKMN
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.yandex.ru
    port: 465
    username: admyaya@yandex.ru
    password: zuslsfazsvjfxjrn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true


jwt:
  secret: mySuperSecretKeydasdas122321123122132dagadfgg
  expiration: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG





setingUsers:
  rolle: USER
  salt: QpwkSlk1kdfDlmui1owd!!3823jf

registerResponse:
  createdUser: Пользователь зарегистрирован но не верефицирован
  userFoundAndNotVerefied: Пользователь уже зарегестрировано но он не верефицирован
  userFound: Пользователь зарегестрирован

errorResponseServer:
  conectedDB: Ошибка сервера подключение к базе данных




